--1) não é para renomear as colunas e sim criar da maneira correta desde a primeira vez.
--1.R) Feito!
--2) DDL e DML (Deixa os scripts )
--2.R) Data Definition Language (DDL), se refere mais a códigos que mudam a estrutura de dados,
--como criação e exclusão de tabelas e funções que auxiliarão na manipulação. 
-- Data Manipulation Language, se refere a códiogo de exploração dos dados, onde não 
-- exatamente será alterada a estrutura principal, no máximo excluir ou acrescentar dados em linhas.  
--3) os novos nome de coluna, não está legal (não é gramaticalmente)
--3.R) Os nomes das tabelas foram colocados no plural
--4) existe uma forma que escreve menos no momento do insert
--4.R) Feito!
--5) criar mais funcoes para select composto
--5) Feito!
--6) quero uma funcao onde eu rode pessoaMaisNova();
--6.R) Feito!
--7) pessoaMaisVelha();
--7.R) Feito!
--8) como boa pratica nome de tabela deve ser no plural ou singular?
--8.R) É melhor deixar no plural, já que há vários registros de usuários ao invés de um.
